/* Appwrite 控制台中文汉化脚本
 * 通过 MutationObserver 监听 DOM 变化，将英文文本替换为中文
 * 注入方式：nginx sub_filter 在 /console/ 的 HTML 中插入 <script src="/appwrite-zh.js"></script>
 */
(function () {
  'use strict';

  // 翻译映射表：精确匹配（trim 后全等）
  const TRANSLATIONS = {
    // === 顶部/全局 ===
    'Feedback': '反馈',
    'Support': '支持',
    'Docs': '文档',
    'Terms': '服务条款',
    'Privacy': '隐私政策',
    'Connect': '连接',
    'Get started': '开始使用',
    'Toggle Command Center': '打开命令中心',
    'Open organizations tab': '打开组织列表',
    'Open projects tab': '打开项目列表',
    'Invite': '邀请',
    'Create project': '创建项目',
    'Projects': '项目',
    'Members': '成员',
    'Search by name, label, or ID': '按名称、标签或 ID 搜索',

    // === 左侧导航 ===
    'Overview': '概览',
    'Auth': '认证',
    'Databases': '数据库',
    'Functions': '云函数',
    'Messaging': '消息',
    'Storage': '存储',
    'Sites': '站点',
    'Settings': '设置',

    // === Overview 子页 ===
    'Platforms': '平台',
    'API keys': 'API 密钥',
    'Dev keys': '开发者密钥',
    'Add platform': '添加平台',
    'Documentation': '文档',
    'View API keys': '查看 API 密钥',
    'DATABASE': '数据库',
    'STORAGE': '存储',
    'AUTH': '认证',
    'FUNCTIONS': '云函数',

    // === Auth 子页 ===
    'Users': '用户',
    'Teams': '团队',
    'Security': '安全',
    'Templates': '模板',
    'Create user': '创建用户',
    'Search by name, email, phone, or ID': '按姓名、邮箱、电话或 ID 搜索',
    'Unverified': '未验证',
    'Verified': '已验证',

    // === Settings 子页 ===
    'Custom domains': '自定义域名',
    'Webhooks': 'Web 钩子',
    'Migrations': '数据迁移',
    'SMTP': 'SMTP 邮件',
    'Update': '更新',
    'Save': '保存',
    'Cancel': '取消',
    'Delete': '删除',
    'Edit': '编辑',
    'Enable all': '全部启用',
    'Disable all': '全部禁用',
    'Select or type project labels': '选择或输入项目标签',
    'live': '线上',
    'stage': '预发布',
    'internal': '内部',

    // === 通用按钮/操作 ===
    'Create': '创建',
    'Add': '添加',
    'Remove': '移除',
    'Confirm': '确认',
    'Close': '关闭',
    'Back': '返回',
    'Next': '下一页',
    'Prev': '上一页',
    'Search': '搜索',
    'Filter': '筛选',
    'Actions': '操作',
    'Name': '名称',
    'Email': '邮箱',
    'Status': '状态',
    'Created': '创建时间',
    'Updated': '更新时间',
    'ID': 'ID',
    'Enabled': '已启用',
    'Disabled': '已禁用',
    'Active': '活跃',
    'Inactive': '未激活',
    'Loading': '加载中',
    'No results': '无结果',
    'No data': '暂无数据',
    'Total': '总计',
    'Size': '大小',
    'Type': '类型',
    'File': '文件',
    'Files': '文件',
    'Bucket': '存储桶',
    'Buckets': '存储桶',
    'Collection': '集合',
    'Collections': '集合',
    'Document': '文档',
    'Documents': '文档',
    'Attribute': '属性',
    'Attributes': '属性',
    'Index': '索引',
    'Indexes': '索引',
    'Permission': '权限',
    'Permissions': '权限',
    'Key': '密钥',
    'Keys': '密钥',
    'Secret': '密钥',
    'Endpoint': '端点',
    'Project': '项目',
    'Organization': '组织',
    'Description': '描述',
    'Expires': '过期时间',
    'Created at': '创建时间',
    'Updated at': '更新时间',
    'Last accessed': '最后访问',
    'Role': '角色',
    'Owner': '所有者',
    'Admin': '管理员',
    'Member': '成员',
    'Guest': '访客',
    'All users': '所有用户',
    'Guests': '访客',
    'Users': '用户',
    'Teams': '团队',
    'Label': '标签',
    'Labels': '标签',
    'Region': '区域',
    'Runtime': '运行时',
    'Execution': '执行',
    'Executions': '执行记录',
    'Deployments': '部署',
    'Variables': '变量',
    'Schedule': '定时',
    'Timeout': '超时',
    'Events': '事件',
    'Logs': '日志',
    'Usage': '用量',
    'Statistics': '统计',
    'General': '常规',
    'Advanced': '高级',
    'Danger zone': '危险操作',
    'Are you sure?': '确定要执行此操作吗？',
    'Yes': '是',
    'No': '否',
    'OK': '确定',
    'Submit': '提交',
    'Reset': '重置',
    'Refresh': '刷新',
    'Reload': '重新加载',
    'Copy': '复制',
    'Copied': '已复制',
    'Download': '下载',
    'Upload': '上传',
    'Preview': '预览',
    'View': '查看',
    'Hide': '隐藏',
    'Show': '显示',
    'More': '更多',
    'Less': '收起',
    'Expand': '展开',
    'Collapse': '折叠',
    'Select all': '全选',
    'Deselect all': '取消全选',
    'Selected': '已选中',
    'Bulk actions': '批量操作',
    'Export': '导出',
    'Import': '导入',
    'Generate': '生成',
    'Regenerate': '重新生成',
    'Revoke': '撤销',
    'Suspend': '暂停',
    'Unsuspend': '恢复',
    'Block': '封禁',
    'Unblock': '解封',
    'Ban': '封禁',
    'Unban': '解封',
    'Verify': '验证',
    'Unverify': '取消验证',
    'Reset password': '重置密码',
    'Change password': '修改密码',
    'Password': '密码',
    'Confirm password': '确认密码',
    'New password': '新密码',
    'Current password': '当前密码',
    'Old password': '旧密码',
    'Phone': '手机号',
    'Username': '用户名',
    'First name': '名',
    'Last name': '姓',
    'Full name': '姓名',
    'Display name': '显示名称',
    'Avatar': '头像',
    'Profile': '个人资料',
    'Account': '账号',
    'Billing': '账单',
    'Subscription': '订阅',
    'Plan': '套餐',
    'Upgrade': '升级',
    'Downgrade': '降级',
    'Cancel subscription': '取消订阅',
    'Renew': '续费',
    'Expired': '已过期',
    'Trial': '试用',
    'Free': '免费',
    'Pro': '专业版',
    'Enterprise': '企业版',
    'Custom': '自定义',
    'Default': '默认',
    'None': '无',
    'All': '全部',
    'Any': '任意',
    'Required': '必填',
    'Optional': '可选',
    'Public': '公开',
    'Private': '私有',
    'Read': '读取',
    'Write': '写入',
    'Create': '创建',
    'Delete': '删除',
    'Update': '更新',
    'Read only': '只读',
    'Read and write': '读写',
    'Admin access': '管理员权限',
    'No access': '无权限',
    'Owner access': '所有者权限',
    'Member access': '成员权限',
    'Guest access': '访客权限',
    'Anyone': '任何人',
    'Signed in users': '已登录用户',
    'Team members': '团队成员',
    'Team owners': '团队所有者',
    'Team admins': '团队管理员',
    'User': '用户',
    'Team': '团队',
    'Member': '成员',
    'Invited': '已邀请',
    'Joined': '已加入',
    'Pending': '待处理',
    'Approved': '已批准',
    'Rejected': '已拒绝',
    'Processing': '处理中',
    'Completed': '已完成',
    'Failed': '失败',
    'Success': '成功',
    'Error': '错误',
    'Warning': '警告',
    'Info': '信息',
    'Debug': '调试',
    'Critical': '严重',
    'Emergency': '紧急',
    'Notice': '通知',
    'Alert': '警报',
    'Message': '消息',
    'Notification': '通知',
    'Notifications': '通知',
    'Inbox': '收件箱',
    'Sent': '已发送',
    'Draft': '草稿',
    'Archive': '归档',
    'Trash': '回收站',
    'Spam': '垃圾邮件',
    'Starred': '已加星标',
    'Important': '重要',
    'Unread': '未读',
    'Read': '已读',
    'Replied': '已回复',
    'Forwarded': '已转发',
    'Attachment': '附件',
    'Attachments': '附件',
    'Subject': '主题',
    'Body': '正文',
    'Sender': '发件人',
    'Recipient': '收件人',
    'Recipients': '收件人',
    'CC': '抄送',
    'BCC': '密送',
    'Reply': '回复',
    'Reply all': '全部回复',
    'Forward': '转发',
    'Compose': '撰写',
    'New message': '新消息',
    'Send': '发送',
    'Sending': '发送中',
    'Sent at': '发送时间',
    'Received at': '接收时间',
    'Read at': '阅读时间',
    'Delivered': '已送达',
    'Delivery': '送达',
    'Bounce': '退信',
    'Bounced': '已退信',
    'Open': '打开',
    'Opened': '已打开',
    'Click': '点击',
    'Clicked': '已点击',
    'Conversion': '转化',
    'Converted': '已转化',
    'Revenue': '收入',
    'Cost': '成本',
    'Profit': '利润',
    'Margin': '利润率',
    'ROI': '投资回报率',
    'ROAS': '广告支出回报率',
    'CTR': '点击率',
    'CPC': '单次点击成本',
    'CPM': '千次展示成本',
    'CPA': '单次转化成本',
    'LTV': '用户终身价值',
    'CAC': '用户获取成本',
    'Churn': '流失',
    'Churn rate': '流失率',
    'Retention': '留存',
    'Retention rate': '留存率',
    'Engagement': '参与度',
    'Active users': '活跃用户',
    'New users': '新用户',
    'Returning users': '回访用户',
    'Sessions': '会话',
    'Session duration': '会话时长',
    'Page views': '页面浏览量',
    'Unique visitors': '独立访客',
    'Bounce rate': '跳出率',
    'Conversion rate': '转化率',
    'Average order value': '平均订单价值',
    'Customer lifetime value': '客户终身价值',
    'Monthly recurring revenue': '月度经常性收入',
    'Annual recurring revenue': '年度经常性收入',
    'MRR': '月度经常性收入',
    'ARR': '年度经常性收入',
    'GMV': '商品交易总额',
    'DAU': '日活跃用户',
    'WAU': '周活跃用户',
    'MAU': '月活跃用户',
    'ARPU': '每用户平均收入',
    'ARPPU': '每付费用户平均收入',
    'NPS': '净推荐值',
    'CSAT': '客户满意度',
    'CES': '客户费力度',
    'FCR': '首次解决率',
    'AHT': '平均处理时长',
    'FRT': '首次响应时间',
    'SLA': '服务等级协议',
    'SLA compliance': 'SLA 达标率',
    'Uptime': '正常运行时间',
    'Downtime': '停机时间',
    'Availability': '可用性',
    'Reliability': '可靠性',
    'Performance': '性能',
    'Latency': '延迟',
    'Throughput': '吞吐量',
    'Bandwidth': '带宽',
    'Storage': '存储',
    'Memory': '内存',
    'CPU': '处理器',
    'Disk': '磁盘',
    'Network': '网络',
    'Traffic': '流量',
    'Requests': '请求数',
    'Response time': '响应时间',
    'Error rate': '错误率',
    'Success rate': '成功率',
    'Apdex': '应用性能指数',
    'SLO': '服务等级目标',
    'SLI': '服务等级指标',
    'Error budget': '错误预算',
    'Burn rate': '消耗率',
    'MTTR': '平均恢复时间',
    'MTBF': '平均故障间隔',
    'MTTD': '平均检测时间',
    'MTTA': '平均响应时间',
    'Incident': '事件',
    'Incidents': '事件',
    'Problem': '问题',
    'Problems': '问题',
    'Change': '变更',
    'Changes': '变更',
    'Release': '发布',
    'Releases': '发布',
    'Deployment': '部署',
    'Deployments': '部署',
    'Pipeline': '流水线',
    'Pipelines': '流水线',
    'Build': '构建',
    'Builds': '构建',
    'Test': '测试',
    'Tests': '测试',
    'QA': '质量保证',
    'Staging': '预发布环境',
    'Production': '生产环境',
    'Development': '开发环境',
    'Environment': '环境',
    'Environments': '环境',
    'Config': '配置',
    'Configuration': '配置',
    'Configurations': '配置',
    'Variable': '变量',
    'Variables': '变量',
    'Secret': '密钥',
    'Secrets': '密钥',
    'Credential': '凭证',
    'Credentials': '凭证',
    'Certificate': '证书',
    'Certificates': '证书',
    'Domain': '域名',
    'Domains': '域名',
    'DNS': '域名解析',
    'SSL': 'SSL 证书',
    'TLS': 'TLS 证书',
    'HTTPS': 'HTTPS',
    'HTTP': 'HTTP',
    'TCP': 'TCP',
    'UDP': 'UDP',
    'IP': 'IP 地址',
    'IPv4': 'IPv4 地址',
    'IPv6': 'IPv6 地址',
    'Port': '端口',
    'Ports': '端口',
    'Protocol': '协议',
    'Protocols': '协议',
    'Method': '方法',
    'Methods': '方法',
    'Header': '请求头',
    'Headers': '请求头',
    'Parameter': '参数',
    'Parameters': '参数',
    'Query': '查询',
    'Query string': '查询字符串',
    'Path': '路径',
    'URL': '网址',
    'URI': '资源标识符',
    'URN': '资源名称',
    'Host': '主机',
    'Hostname': '主机名',
    'Origin': '来源',
    'Referer': '来源页',
    'User agent': '用户代理',
    'Cookie': 'Cookie',
    'Cookies': 'Cookies',
    'Session': '会话',
    'Sessions': '会话',
    'Token': '令牌',
    'Tokens': '令牌',
    'JWT': 'JWT 令牌',
    'OAuth': 'OAuth 认证',
    'SSO': '单点登录',
    'SAML': 'SAML 认证',
    'LDAP': 'LDAP 认证',
    'MFA': '多因素认证',
    '2FA': '双因素认证',
    'TOTP': '基于时间的一次性密码',
    'HOTP': '基于计数器的一次性密码',
    'SMS': '短信',
    'Email': '邮箱',
    'Phone': '电话',
    'Authenticator app': '身份验证器应用',
    'Recovery code': '恢复代码',
    'Recovery codes': '恢复代码',
    'Backup code': '备用代码',
    'Backup codes': '备用代码',
    'Security key': '安全密钥',
    'Biometric': '生物识别',
    'Face ID': '面容 ID',
    'Touch ID': '触控 ID',
    'Windows Hello': 'Windows Hello',
    'Passkey': '通行密钥',
    'Passwordless': '无密码',
    'Magic link': '魔法链接',
    'OTP': '一次性密码',
    'PIN': 'PIN 码',
    'Pattern': '图案',
    'Gesture': '手势',
    'Voice': '语音',
    'Face': '人脸',
    'Fingerprint': '指纹',
    'Iris': '虹膜',
    'Retina': '视网膜',
    'Behavioral': '行为特征',
    'Location': '位置',
    'Geolocation': '地理位置',
    'GPS': 'GPS 定位',
    'IP address': 'IP 地址',
    'MAC address': 'MAC 地址',
    'Device': '设备',
    'Devices': '设备',
    'Device ID': '设备 ID',
    'Device name': '设备名称',
    'Device type': '设备类型',
    'Device model': '设备型号',
    'OS': '操作系统',
    'Operating system': '操作系统',
    'Browser': '浏览器',
    'Browser version': '浏览器版本',
    'App version': '应用版本',
    'SDK version': 'SDK 版本',
    'API version': 'API 版本',
    'Version': '版本',
    'Versions': '版本',
    'Revision': '修订版',
    'Revisions': '修订版',
    'Commit': '提交',
    'Commits': '提交',
    'Branch': '分支',
    'Branches': '分支',
    'Tag': '标签',
    'Tags': '标签',
    'Release': '发布',
    'Releases': '发布',
    'Pull request': '拉取请求',
    'Pull requests': '拉取请求',
    'Merge request': '合并请求',
    'Merge requests': '合并请求',
    'Issue': '问题',
    'Issues': '问题',
    'Bug': '缺陷',
    'Bugs': '缺陷',
    'Feature': '功能',
    'Features': '功能',
    'Enhancement': '增强',
    'Improvement': '改进',
    'Task': '任务',
    'Tasks': '任务',
    'Todo': '待办',
    'Todos': '待办',
    'Backlog': '待办列表',
    'Sprint': '冲刺',
    'Sprints': '冲刺',
    'Epic': '史诗',
    'Epics': '史诗',
    'Story': '故事',
    'Stories': '故事',
    'Story point': '故事点',
    'Story points': '故事点',
    'Velocity': '速率',
    'Capacity': '容量',
    'Workload': '工作量',
    'Effort': '工作量',
    'Estimate': '估算',
    'Estimates': '估算',
    'Actual': '实际',
    'Remaining': '剩余',
    'Completed': '已完成',
    'In progress': '进行中',
    'In review': '审核中',
    'In testing': '测试中',
    'Blocked': '已阻塞',
    'On hold': '已暂停',
    'Cancelled': '已取消',
    'Canceled': '已取消',
    'Closed': '已关闭',
    'Open': '待处理',
    'Reopened': '重新打开',
    'Resolved': '已解决',
    'Unresolved': '未解决',
    'Confirmed': '已确认',
    'Unconfirmed': '未确认',
    'Triaged': '已分诊',
    'Untriaged': '未分诊',
    'Assigned': '已分配',
    'Unassigned': '未分配',
    'Assignee': '负责人',
    'Assignees': '负责人',
    'Reporter': '报告人',
    'Creator': '创建者',
    'Created by': '创建者',
    'Updated by': '更新者',
    'Assigned to': '分配给',
    'Due date': '截止日期',
    'Start date': '开始日期',
    'End date': '结束日期',
    'Target date': '目标日期',
    'Original estimate': '原始估算',
    'Remaining estimate': '剩余估算',
    'Time spent': '已用时间',
    'Time tracking': '时间追踪',
    'Worklog': '工作日志',
    'Worklogs': '工作日志',
    'Comment': '评论',
    'Comments': '评论',
    'Activity': '动态',
    'History': '历史记录',
    'Changelog': '变更日志',
    'Attachment': '附件',
    'Attachments': '附件',
    'Sub-task': '子任务',
    'Sub-tasks': '子任务',
    'Subtask': '子任务',
    'Subtasks': '子任务',
    'Parent': '父任务',
    'Parent task': '父任务',
    'Child': '子任务',
    'Child task': '子任务',
    'Related': '相关',
    'Related issues': '相关问题',
    'Linked': '已关联',
    'Links': '关联',
    'Dependency': '依赖',
    'Dependencies': '依赖',
    'Blocks': '阻塞',
    'Blocked by': '被阻塞',
    'Cloners': '克隆',
    'Clones': '克隆',
    'Duplicate': '重复',
    'Duplicates': '重复',
    'Is duplicated by': '被重复',
    'Regression': '回归',
    'Regressions': '回归',
    'Cause': '原因',
    'Causes': '原因',
    'Caused by': '由...引起',
    'Reference': '参考',
    'References': '参考',
    'See also': '另见',
    'Part of': '属于',
    'Contains': '包含',
    'Container': '容器',
    'Containers': '容器',
    'Image': '镜像',
    'Images': '镜像',
    'Registry': '镜像仓库',
    'Repositories': '仓库',
    'Repository': '仓库',
    'Artifact': '制品',
    'Artifacts': '制品',
    'Package': '包',
    'Packages': '包',
    'Module': '模块',
    'Modules': '模块',
    'Library': '库',
    'Libraries': '库',
    'Framework': '框架',
    'Frameworks': '框架',
    'Plugin': '插件',
    'Plugins': '插件',
    'Extension': '扩展',
    'Extensions': '扩展',
    'Add-on': '附加组件',
    'Add-ons': '附加组件',
    'Theme': '主题',
    'Themes': '主题',
    'Template': '模板',
    'Templates': '模板',
    'Preset': '预设',
    'Presets': '预设',
    'Profile': '配置文件',
    'Profiles': '配置文件',
    'Config': '配置',
    'Configs': '配置',
    'Setting': '设置',
    'Settings': '设置',
    'Preference': '偏好',
    'Preferences': '偏好',
    'Option': '选项',
    'Options': '选项',
    'Toggle': '开关',
    'Switch': '开关',
    'Checkbox': '复选框',
    'Radio': '单选按钮',
    'Dropdown': '下拉菜单',
    'Select': '选择',
    'Picker': '选择器',
    'Date picker': '日期选择器',
    'Time picker': '时间选择器',
    'Color picker': '颜色选择器',
    'Slider': '滑块',
    'Range': '范围',
    'Number': '数字',
    'Text': '文本',
    'Textarea': '文本域',
    'Field': '字段',
    'Fields': '字段',
    'Form': '表单',
    'Forms': '表单',
    'Validation': '验证',
    'Valid': '有效',
    'Invalid': '无效',
    'Error': '错误',
    'Errors': '错误',
    'Warning': '警告',
    'Warnings': '警告',
    'Success': '成功',
    'Info': '信息',
    'Hint': '提示',
    'Tip': '提示',
    'Help': '帮助',
    'Tooltip': '工具提示',
    'Placeholder': '占位符',
    'Default value': '默认值',
    'Required': '必填',
    'Optional': '可选',
    'Read only': '只读',
    'Disabled': '已禁用',
    'Enabled': '已启用',
    'Hidden': '已隐藏',
    'Visible': '可见',
    'Collapsed': '已折叠',
    'Expanded': '已展开',
    'Selected': '已选中',
    'Focused': '已聚焦',
    'Hovered': '悬停',
    'Active': '活跃',
    'Inactive': '未激活',
    'Loading': '加载中',
    'Loaded': '已加载',
    'Saving': '保存中',
    'Saved': '已保存',
    'Submitting': '提交中',
    'Submitted': '已提交',
    'Processing': '处理中',
    'Processed': '已处理',
    'Deleting': '删除中',
    'Deleted': '已删除',
    'Updating': '更新中',
    'Updated': '已更新',
    'Creating': '创建中',
    'Created': '已创建',
    'Editing': '编辑中',
    'Edited': '已编辑',
    'Copying': '复制中',
    'Copied': '已复制',
    'Downloading': '下载中',
    'Downloaded': '已下载',
    'Uploading': '上传中',
    'Uploaded': '已上传',
    'Importing': '导入中',
    'Imported': '已导入',
    'Exporting': '导出中',
    'Exported': '已导出',
    'Generating': '生成中',
    'Generated': '已生成',
    'Refreshing': '刷新中',
    'Refreshed': '已刷新',
    'Syncing': '同步中',
    'Synced': '已同步',
    'Connecting': '连接中',
    'Connected': '已连接',
    'Disconnecting': '断开中',
    'Disconnected': '已断开',
    'Authenticating': '认证中',
    'Authenticated': '已认证',
    'Unauthenticated': '未认证',
    'Authorizing': '授权中',
    'Authorized': '已授权',
    'Unauthorized': '未授权',
    'Forbidden': '禁止访问',
    'Not found': '未找到',
    'Page not found': '页面未找到',
    '404 Page not found': '404 页面未找到',
    'The page you\'re looking for doesn\'t exist.': '您访问的页面不存在。',
    'Back to console': '返回控制台',
    'Build like a team of hundreds_': '像百人团队一样构建_',
    'No apps': '暂无应用',
    '33% complete': '完成 33%',
    'complete': '完成',
    '% complete': '完成度',
    'An hour ago': '一小时前',
    'minutes ago': '分钟前',
    'hours ago': '小时前',
    'days ago': '天前',
    'weeks ago': '周前',
    'months ago': '月前',
    'years ago': '年前',
    'Just now': '刚刚',
    'Yesterday': '昨天',
    'Today': '今天',
    'Tomorrow': '明天',
    'Last week': '上周',
    'This week': '本周',
    'Next week': '下周',
    'Last month': '上个月',
    'This month': '本月',
    'Next month': '下个月',
    'Last year': '去年',
    'This year': '今年',
    'Next year': '明年',
    'Monday': '星期一',
    'Tuesday': '星期二',
    'Wednesday': '星期三',
    'Thursday': '星期四',
    'Friday': '星期五',
    'Saturday': '星期六',
    'Sunday': '星期日',
    'January': '一月',
    'February': '二月',
    'March': '三月',
    'April': '四月',
    'May': '五月',
    'June': '六月',
    'July': '七月',
    'August': '八月',
    'September': '九月',
    'October': '十月',
    'November': '十一月',
    'December': '十二月',
  };

  // 包含匹配（用于较长的描述性文本，包含关键词即翻译）
  const CONTAINS_TRANSLATIONS = [
    { pattern: /^Search by /, replace: '按' },
  ];

  // 已处理的文本节点集合（避免重复处理）
  const processedNodes = new WeakSet();

  // 翻译单个文本节点
  function translateTextNode(node) {
    if (processedNodes.has(node)) return;
    const original = node.textContent;
    if (!original || !original.trim()) return;

    const trimmed = original.trim();
    let translated = null;

    // 精确匹配
    if (TRANSLATIONS[trimmed]) {
      translated = TRANSLATIONS[trimmed];
    }

    if (translated !== null && translated !== trimmed) {
      node.textContent = original.replace(trimmed, translated);
      processedNodes.add(node);
    }
  }

  // 翻译元素的属性（placeholder, title, aria-label 等）
  function translateElementAttributes(el) {
    const attrs = ['placeholder', 'title', 'aria-label', 'aria-placeholder'];
    for (const attr of attrs) {
      const val = el.getAttribute(attr);
      if (val && TRANSLATIONS[val.trim()]) {
        el.setAttribute(attr, TRANSLATIONS[val.trim()]);
      }
    }
  }

  // 遍历 DOM 树，翻译所有文本节点和属性
  function translateDOM(root) {
    if (!root) return;

    // 翻译文本节点
    const walker = document.createTreeWalker(
      root,
      NodeFilter.SHOW_TEXT,
      {
        acceptNode: function (node) {
          // 跳过 script、style、noscript 中的文本
          const parent = node.parentElement;
          if (parent && (parent.tagName === 'SCRIPT' || parent.tagName === 'STYLE' || parent.tagName === 'NOSCRIPT')) {
            return NodeFilter.FILTER_REJECT;
          }
          // 跳过纯空白节点
          if (!node.textContent.trim()) return NodeFilter.FILTER_REJECT;
          return NodeFilter.FILTER_ACCEPT;
        }
      }
    );

    let node;
    while ((node = walker.nextNode())) {
      translateTextNode(node);
    }

    // 翻译元素属性
    if (root.querySelectorAll) {
      const elements = root.querySelectorAll('[placeholder],[title],[aria-label],[aria-placeholder]');
      elements.forEach(translateElementAttributes);
    }
    if (root.nodeType === Node.ELEMENT_NODE) {
      translateElementAttributes(root);
    }

    // 翻译页面标题
    if (document.title && TRANSLATIONS[document.title.trim()]) {
      document.title = TRANSLATIONS[document.title.trim()];
    }
  }

  // 防抖翻译
  let translateTimer = null;
  function scheduleTranslate(root) {
    if (translateTimer) clearTimeout(translateTimer);
    translateTimer = setTimeout(function () {
      translateDOM(root || document.body);
    }, 50);
  }

  // 初始化：等待 DOM 就绪后开始翻译
  function init() {
    // 首次翻译
    translateDOM(document.body);

    // 监听 DOM 变化（Appwrite 控制台是 SPA，内容动态加载）
    const observer = new MutationObserver(function (mutations) {
      for (const mutation of mutations) {
        if (mutation.type === 'childList') {
          for (const node of mutation.addedNodes) {
            if (node.nodeType === Node.ELEMENT_NODE || node.nodeType === Node.TEXT_NODE) {
              scheduleTranslate(node);
            }
          }
        } else if (mutation.type === 'characterData') {
          translateTextNode(mutation.target);
        }
      }
      // 整体也扫一遍，防止遗漏
      scheduleTranslate(document.body);
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
      characterData: true,
    });

    // 监听 URL 变化（SPA 路由切换）
    let lastUrl = location.href;
    setInterval(function () {
      if (location.href !== lastUrl) {
        lastUrl = location.href;
        setTimeout(function () { translateDOM(document.body); }, 300);
      }
    }, 500);

    console.log('[Appwrite 汉化] 已加载');
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
