-- 多设备会话控制与实时同步游标。
BEGIN;
SELECT pg_advisory_xact_lock(70420260923);

ALTER TABLE app.user_accounts ADD COLUMN IF NOT EXISTS max_active_sessions integer NOT NULL DEFAULT 5 CHECK (max_active_sessions BETWEEN 1 AND 50);
ALTER TABLE app.outbox_events ADD COLUMN IF NOT EXISTS sequence_no bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS outbox_events_sequence_idx ON app.outbox_events(sequence_no);

CREATE TABLE IF NOT EXISTS app.sync_cursors (
    device_id uuid NOT NULL,
    user_id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    last_sequence bigint NOT NULL DEFAULT 0 CHECK (last_sequence >= 0),
    version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (device_id, workspace_id),
    FOREIGN KEY (device_id, user_id) REFERENCES app.user_devices(id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (workspace_id) REFERENCES app.workspaces(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS app.session_actions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_user_id uuid NOT NULL REFERENCES app.user_accounts(id) ON DELETE RESTRICT,
    target_user_id uuid NOT NULL REFERENCES app.user_accounts(id) ON DELETE RESTRICT,
    target_session_id uuid REFERENCES app.user_sessions(id) ON DELETE SET NULL,
    action_type text NOT NULL CHECK (action_type IN ('revoke_one','revoke_others','revoke_all','admit','deny')),
    reason varchar(160),
    request_id varchar(160) UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE app.sync_cursors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sync_cursor_self_isolation ON app.sync_cursors;
CREATE POLICY sync_cursor_self_isolation ON app.sync_cursors
    USING (user_id = app.current_user_id())
    WITH CHECK (user_id = app.current_user_id());

CREATE OR REPLACE FUNCTION app.revoke_other_sessions(p_except_session_id uuid, p_reason varchar DEFAULT 'user_request')
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = app, pg_temp AS $$
DECLARE u uuid; affected integer;
BEGIN
    u := app.current_user_id();
    IF u IS NULL THEN RAISE EXCEPTION '没有登录身份'; END IF;
    UPDATE app.user_sessions
       SET admission_status='revoked', revoked_at=now(), revoked_reason=p_reason,
           provider_revocation_status='pending', revoke_retry_at=now()
     WHERE user_id=u AND admission_status IN ('pending','active')
       AND (p_except_session_id IS NULL OR id <> p_except_session_id);
    GET DIAGNOSTICS affected = ROW_COUNT;
    INSERT INTO app.session_actions(actor_user_id,target_user_id,action_type,reason)
      VALUES(u,u,'revoke_others',p_reason);
    RETURN affected;
END $$;

REVOKE ALL ON FUNCTION app.revoke_other_sessions(uuid,varchar) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.revoke_other_sessions(uuid,varchar) TO qingyu_app;
REVOKE ALL ON app.sync_cursors, app.session_actions FROM qingyu_app;

INSERT INTO app.schema_migrations(version, checksum)
VALUES ('0013_sessions_realtime', 'sessions-realtime-v1')
ON CONFLICT (version) DO NOTHING;
COMMIT;
