-- 管理后台模型目录和系统设置进入 PostgreSQL，避免单机 JSON 文件成为数据孤岛。
BEGIN;
SELECT pg_advisory_xact_lock(70420260923);

CREATE TABLE IF NOT EXISTS app.model_catalog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id varchar(160) NOT NULL,
    display_name varchar(240) NOT NULL,
    provider varchar(80) NOT NULL DEFAULT 'unknown',
    capability varchar(32) NOT NULL DEFAULT 'text',
    visible boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT model_catalog_model_id_unique UNIQUE (model_id),
    CONSTRAINT model_catalog_model_id_not_blank CHECK (length(btrim(model_id)) > 0),
    CONSTRAINT model_catalog_display_name_not_blank CHECK (length(btrim(display_name)) > 0)
);
CREATE INDEX IF NOT EXISTS model_catalog_visible_order_idx ON app.model_catalog(visible, sort_order, id);

CREATE TABLE IF NOT EXISTS app.system_settings (
    setting_key varchar(120) PRIMARY KEY,
    setting_value jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION app.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS model_catalog_touch_updated ON app.model_catalog;
CREATE TRIGGER model_catalog_touch_updated
BEFORE UPDATE ON app.model_catalog
FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();

DROP TRIGGER IF EXISTS system_settings_touch_updated ON app.system_settings;
CREATE TRIGGER system_settings_touch_updated
BEFORE UPDATE ON app.system_settings
FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();

ALTER TABLE app.model_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.system_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS model_catalog_admin_access ON app.model_catalog;
DROP POLICY IF EXISTS system_settings_admin_access ON app.system_settings;
CREATE POLICY model_catalog_admin_access ON app.model_catalog FOR ALL USING (current_user IN ('qingyu_api','postgres')) WITH CHECK (current_user IN ('qingyu_api','postgres'));
CREATE POLICY system_settings_admin_access ON app.system_settings FOR ALL USING (current_user IN ('qingyu_api','postgres')) WITH CHECK (current_user IN ('qingyu_api','postgres'));
GRANT SELECT, INSERT, UPDATE, DELETE ON app.model_catalog TO qingyu_api;
GRANT USAGE, SELECT ON SEQUENCE app.model_catalog_id_seq TO qingyu_api;
GRANT SELECT, INSERT, UPDATE, DELETE ON app.system_settings TO qingyu_api;

INSERT INTO app.schema_migrations(version, checksum)
VALUES ('0051_admin_catalog_settings', 'admin-catalog-settings-v1')
ON CONFLICT (version) DO NOTHING;
COMMIT;
