-- 模型目录使用平台自增编号；供应商模型通过独立关系关联，不要求管理员手填 model_id。
BEGIN;
SELECT pg_advisory_xact_lock(70420260923);

ALTER TABLE app.model_catalog ALTER COLUMN model_id DROP NOT NULL;
ALTER TABLE app.model_catalog DROP CONSTRAINT IF EXISTS model_catalog_model_id_not_blank;

CREATE TABLE IF NOT EXISTS app.model_catalog_channel_models (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_catalog_id bigint NOT NULL REFERENCES app.model_catalog(id) ON DELETE CASCADE,
    platform_api_key_id uuid NOT NULL REFERENCES app.platform_api_keys(id) ON DELETE CASCADE,
    upstream_model_id varchar(240) NOT NULL,
    priority integer NOT NULL DEFAULT 0 CHECK (priority >= 0),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT model_catalog_channel_model_unique UNIQUE (model_catalog_id, platform_api_key_id, upstream_model_id),
    CONSTRAINT model_catalog_upstream_model_not_blank CHECK (length(btrim(upstream_model_id)) > 0)
);
CREATE INDEX IF NOT EXISTS model_catalog_channel_models_route_idx
    ON app.model_catalog_channel_models(model_catalog_id, is_active, priority, id);
CREATE INDEX IF NOT EXISTS model_catalog_channel_models_channel_idx
    ON app.model_catalog_channel_models(platform_api_key_id, is_active);

-- 把迁移时已配置的上游模型登记为默认可见目录项，避免新目录切换后现有模型突然消失。
INSERT INTO app.model_catalog(model_id, display_name, provider, capability, sort_order)
SELECT DISTINCT ON (btrim(model_name))
    btrim(model_name), btrim(model_name), pak.provider,
    CASE
      WHEN lower(btrim(model_name)) ~ '(video|sora|veo|kling|wan|hailuo|seedance)' THEN 'video'
      WHEN lower(btrim(model_name)) ~ '(audio|speech|tts|voice|music)' THEN 'audio'
      WHEN lower(btrim(model_name)) ~ '(image|dall.?e|flux|sdxl|imagen|seedream|banana)' THEN 'image'
      ELSE 'text'
    END,
    0
FROM app.platform_api_keys pak
CROSS JOIN LATERAL regexp_split_to_table(coalesce(pak.model, ''), ',') AS model_name
WHERE btrim(model_name) <> ''
ORDER BY btrim(model_name), pak.updated_at DESC, pak.id
ON CONFLICT (model_id) DO NOTHING;

-- 兼容已有目录：若目录 model_id 与某条渠道配置的模型名一致，自动建立原有可确认的关系。
INSERT INTO app.model_catalog_channel_models(model_catalog_id, platform_api_key_id, upstream_model_id)
SELECT DISTINCT mc.id, pak.id, btrim(model_name)
FROM app.model_catalog mc
JOIN app.platform_api_keys pak ON true
CROSS JOIN LATERAL regexp_split_to_table(coalesce(pak.model, ''), ',') AS model_name
WHERE btrim(model_name) <> '' AND mc.model_id = btrim(model_name)
  AND (CASE WHEN lower(pak.provider) = 'gemini' THEN 'gemini' ELSE 'openai' END)
      = (CASE WHEN lower(mc.provider) = 'gemini' THEN 'gemini' ELSE 'openai' END)
ON CONFLICT (model_catalog_id, platform_api_key_id, upstream_model_id) DO NOTHING;

ALTER TABLE app.model_catalog_channel_models ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS model_catalog_channel_models_admin_access ON app.model_catalog_channel_models;
CREATE POLICY model_catalog_channel_models_admin_access ON app.model_catalog_channel_models
    FOR ALL USING (current_user IN ('qingyu_api','postgres'))
    WITH CHECK (current_user IN ('qingyu_api','postgres'));
GRANT SELECT, INSERT, UPDATE, DELETE ON app.model_catalog_channel_models TO qingyu_api;
GRANT USAGE, SELECT ON SEQUENCE app.model_catalog_channel_models_id_seq TO qingyu_api;

INSERT INTO app.schema_migrations(version, checksum)
VALUES ('0063_model_catalog_channel_models', 'model-catalog-channel-models-v1')
ON CONFLICT (version) DO NOTHING;
COMMIT;
